// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    partial class NZWalksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c825c1dd-ff1c-4cf4-bb1a-70537656dd6d"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("a0b2fe6c-f29a-4fba-983b-8d6d090260de"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("470a72fd-56c8-447f-bf2e-ea6e5570ab0e"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("345e16f9-4ef7-4dff-a1f5-e347004cd309"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "https://picsum.photos/seed/northland/800/600"
                        },
                        new
                        {
                            Id = new Guid("9c79f272-09bd-44d5-89e1-b75c4e0ea4d2"),
                            Code = "AUK",
                            Name = "Auckland",
                            RegionImageUrl = "https://picsum.photos/seed/auckland/800/600"
                        },
                        new
                        {
                            Id = new Guid("de5197f3-6b64-4388-b818-95d5f2e291cd"),
                            Code = "WKO",
                            Name = "Waikato",
                            RegionImageUrl = "https://picsum.photos/seed/waikato/800/600"
                        },
                        new
                        {
                            Id = new Guid("afb206a0-44b7-4cf4-bf5e-40f00a8c3a3a"),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImageUrl = "https://picsum.photos/seed/bayofplenty/800/600"
                        },
                        new
                        {
                            Id = new Guid("c5ef0cd4-8070-4ed5-981e-7aebba0e880f"),
                            Code = "GIS",
                            Name = "Gisborne",
                            RegionImageUrl = "https://picsum.photos/seed/gisborne/800/600"
                        },
                        new
                        {
                            Id = new Guid("2c1f4af9-060e-4381-aec9-5bf01615455c"),
                            Code = "HKB",
                            Name = "Hawke's Bay",
                            RegionImageUrl = "https://picsum.photos/seed/hawkesbay/800/600"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
